name: Advocatus Build
on:
  push:
    branches:
      - beta
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [16]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: Install Java ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: configure
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
      - name: Setup Maven
        uses: s4u/maven-settings-action@v2.3.0
        with:
          servers: |
            [{
              "id": "royalmind",
              "username": "${{ secrets.PACKAGES_USERNAME }}",
              "password": "${{ secrets.PACKAGES_PASSWORD }}"
            },
            {
              "id": "royalmind-snapshots",
              "username": "${{ secrets.PACKAGES_USERNAME }}",
              "password": "${{ secrets.PACKAGES_PASSWORD }}"
            }]
      - name: build for Java ${{ matrix.java }}
        run: mvn clean javadoc:javadoc package -Dbuild.number=${{ github.run_number }} -B
      - name: deploy for Java ${{ matrix.java }}
        run: mvn javadoc:javadoc deploy -Dbuild.number=${{ github.run_number }} -B -DaltDeploymentRepository=royalmind::default::https://packages.royalmind.net/repository/maven-snapshots/
      # An artifact is generated in a compressed file according to each JDK build version.
      - name: Upload Artifact Colorizer for Java ${{ matrix.java }}
        uses: actions/upload-artifact@v2.2.4
        with:
          name: JDK${{ matrix.java }} Colorizer ${{ github.run_number }}
          path: target/Colorizer.jar