name: Colorizer Build
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: Install Java ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: configure
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
      - name: Setup Maven
        uses: s4u/maven-settings-action@v2.3.0
        with:
          servers: |
            [{
              "id": "royalmind",
              "username": "${{ secrets.PACKAGES_USERNAME }}",
              "password": "${{ secrets.PACKAGES_PASSWORD }}"
            },
            {
              "id": "royalmind-snapshots",
              "username": "${{ secrets.PACKAGES_USERNAME }}",
              "password": "${{ secrets.PACKAGES_PASSWORD }}"
            }]
      - name: deploy for Java ${{ matrix.java }}
        run: mvn javadoc:javadoc deploy -Dbuild.number=${{ github.run_number }} -B